### ISSUE TITLE
Bug: Cursor is misaligned on GNOME Terminal in Ubuntu

### ISSUE THREAD

**Issue by sepsol** [ruby/irb#1118]
Please see the screen recording below to see it in action:

https://github.com/user-attachments/assets/9542b845-0ba3-435a-b9b7-6dd2d9630b1b

_[Asciinema recording](https://asciinema.org/a/g9zYtaaQ5kQTBHL4xEhfyAKwL) (for query-able text-based version)_

 I also tried it in built-in terminal of the Zed Editor (v0.200.4) and the same issue occurred there as well.

**Comment by tompng** [comment]
Asciinema recording raw data shows that IRB printed `"\u001b[0m\u001b[1G\"\u001b[5irb(main):001:0> \u001b[K\u001b[1G"`
Indicating that your `.inputrc` has `emacs-mode-string` setting including `"\e[5`.

```
set show-mode-in-prompt on
set emacs-mode-string "\1\"\e[5"
```

Can you provide your inputrc?
It maybe a bug of [ruby/reline](http://github.com/ruby/reline) interpreting inputrc, or just a misconfiguration of inputrc.

**Comment by sepsol** [comment]
@tompng Here's the content of my `~/.inputrc` file:

```inputrc
set enable-bracketed-paste off
set editing-mode vi
set show-mode-in-prompt on
set vi-cmd-mode-string "\1\033[1 q\2"
set vi-ins-mode-string "\1\033[5 q\2"
```

The issue went away when I commented out the 3rd line:

```inputrc
...
#set show-mode-in-prompt on
...
```

Would you say that was a misconfiguration of this file by me or could it still possibly be a bug?

**Comment by tompng** [comment]
This is caused by two bugs in ruby/reline.

First bug: reading config values that contains space char.
`set vi-cmd-mode-string "\1\033[1 q\2"` is treated as `set vi-cmd-mode-string "\1\033[1`
This is already fixed in https://github.com/ruby/reline/pull/705 and released as reline-0.5.8.

Second bug: wrong CSI regexp pattern.
It was wrong from the beginning, but happens to cause problem from reline-0.6.0
Pull request: https://github.com/ruby/reline/pull/848

I think reline 0.5.8 and 0.5.9 works fine with your inputrc.

**Comment by sepsol** [comment]
I just upgraded from `ruby` 3.2.3 to 3.4.5, `irb` 1.6.2 to 1.14.3, and `reline` 0.3.2 to 0.6.0. That made some difference, but it didn't fully resolve my issue. 

https://github.com/user-attachments/assets/77386b87-0dc4-4a78-96be-edc770ffaa49

_[Asciinema Recording](https://asciinema.org/a/LAnjfIhAgiRKIBnZd6TnVB7A8)_
