### ISSUE TITLE
Paste takes extremely long time, fails

### ISSUE THREAD

**Issue by schneems** [ruby/irb#115]
## Description

Pasting this into irb takes a very long time and never completes

```
thingy = [
{"addon_plan_names"=>[], "app"=>{"id"=>"4f4b0abe-1f20-4a0d-9af0-261cc8eb89e8", "name"=>"hatchet-t-69d71ace9f"}, "created_at"=>"2020-07-27T18:18:41Z", "description"=>"Initial release", "status"=>"succeeded", "id"=>"35d211ed-098a-45bb-a924-e544314d5e6e", "slug"=>nil, "updated_at"=>"2020-07-27T18:18:41Z", "user"=>{"email"=>"developer@example.com", "id"=>"7b1e713f-ad06-4567-a961-fa2a676e3d1f"}, "version"=>1, "current"=>false, "output_stream_url"=>nil}, {"addon_plan_names"=>[], "app"=>{"id"=>"4f4b0abe-1f20-4a0d-9af0-261cc8eb89e8", "name"=>"hatchet-t-69d71ace9f"}, "created_at"=>"2020-07-27T18:18:41Z", "description"=>"Enable Logplex", "status"=>"succeeded", "id"=>"15bdc401-d607-4331-b9ff-77927bfa8d62", "slug"=>nil, "updated_at"=>"2020-07-27T18:18:41Z", "user"=>{"email"=>"developer@example.com", "id"=>"7b1e713f-ad06-4567-a961-fa2a676e3d1f"}, "version"=>2, "current"=>false, "output_stream_url"=>nil}, {"addon_plan_names"=>[], "app"=>{"id"=>"4f4b0abe-1f20-4a0d-9af0-261cc8eb89e8", "name"=>"hatchet-t-69d71ace9f"}, "created_at"=>"2020-07-27T18:18:54Z", "description"=>"Set LANG, RACK_ENV config vars", "status"=>"succeeded", "id"=>"97ed2ce1-1fce-448f-b716-b65f77f819a1", "slug"=>nil, "updated_at"=>"2020-07-27T18:18:54Z", "user"=>{"email"=>"developer@example.com", "id"=>"7b1e713f-ad06-4567-a961-fa2a676e3d1f"}, "version"=>3, "current"=>true, "output_stream_url"=>nil}, {"addon_plan_names"=>[], "app"=>{"id"=>"4f4b0abe-1f20-4a0d-9af0-261cc8eb89e8", "name"=>"hatchet-t-69d71ace9f"}, "created_at"=>"2020-07-27T18:18:54Z", "description"=>"Deploy ab6786ce", "status"=>"failed", "id"=>"d8585c27-133c-4d20-8b71-c3b04096558f", "slug"=>{"id"=>"6986523a-a3ca-4451-8bf5-f0bf72ba5828"}, "updated_at"=>"2020-07-27T18:19:01Z", "user"=>{"email"=>"developer@example.com", "id"=>"7b1e713f-ad06-4567-a961-fa2a676e3d1f"}, "version"=>4, "current"=>false, "output_stream_url"=>"https://example.com/url"}]
```

It pauses/fails in this state:

![](https://www.dropbox.com/s/yg1soy22azgv0bt/Screenshot%202020-07-27%2014.00.35.png?raw=1)

## Terminal Emulator

Iterm2 on mac

## Setting Files

```
$ cat ~/.irbrc
cat: /Users/rschneeman/.irbrc: No such file or directory
⛄ 2.7.1 🚀  ~/Documents/projects/hatchet (schneems/fail-on-release-fail)
$ cat ~/.inputrc
cat: /Users/rschneeman/.inputrc: No such file or directory
$ irb --version
irb 1.2.4 (2020-05-02)
```

**Comment by aycabta** [comment]
The broken behavior is fixed by https://github.com/ruby/reline/pull/170 and https://github.com/ruby/reline/pull/171.

ref. https://github.com/ruby/irb/issues/43

**Comment by schneems** [comment]
Thank you!
>
>

-- 
Richard Schneeman
https://www.schneems.com
he/him

**Comment by estani** [comment]
I'm still seeing this in `1.2.6`. Is it a regression, or it never really worked for term2 & mac?

**Comment by schneems** [comment]
It was fixed when I commented in September 2020. Likely a regression. I confirm pasting the same thing no longer works.
