### ISSUE TITLE
irb fails to start, cannot load "easter-egg"

### ISSUE THREAD

**Issue by LeamHall** [ruby/irb#80]
## Description
**Expected**:  irb starts

**Actual**:   irb
Traceback (most recent call last):
	7: from /usr/local/bin/irb:23:in `<main>'
	6: from /usr/local/bin/irb:23:in `load'
	5: from /usr/local/lib/ruby/gems/2.6.0/gems/irb-1.2.2/exe/irb:9:in `<top (required)>'
	4: from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	3: from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	2: from /usr/local/lib/ruby/gems/2.6.0/gems/irb-1.2.2/lib/irb.rb:24:in `<top (required)>'
	1: from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- irb/easter-egg (LoadError)

## Terminal Emulator       
xterm

## Platform
CentOS 7, patched
Ruby:  ruby 2.6.6p124 (2019-12-18 revision 67836) [x86_64-linux]
Updated OS and Gems this morning. irb worked before the updates.
Mostly worked, the update a week or so ago broke readline. Fixed by copying in readline.so from /usr/local/lib/ruby/2.7.0 to 2.6.0

**Comment by aycabta** [comment]
Thank you for your reporting. I released irb gem 1.2.3 just before.

https://rubygems.org/gems/irb

Would you try again?

**Comment by LeamHall** [comment]
Works now, thanks for the fast response!

**Comment by counterbeing** [comment]
Hey @aycabta. I've just run into this one as well. I'm on version `1.2.3`, ruby version `2.7.1` running on docker.

```
Failure/Error: require File.expand_path('../config/environment', __dir__)

LoadError:
  cannot load such file -- irb/easter-egg
```

I realize this issue is closed, but perhaps the issue persists in some ways? At the very least it's a strange error.

Thanks!

**Comment by aycabta** [comment]
@counterbeing I can't reproduce it with Ruby 2.7.1 and IRB 1.2.3. The problem will occur only on IRB 1.2.2. Would you show smaller environment to reproduce?

**Comment by aycabta** [comment]
@counterbeing Would you check irb gem version in your application's Gemfile.lock that is used in Docker.

**Comment by counterbeing** [comment]
@aycabta Thanks so much for looking into this! After tinkering with it for a while, I think I was actually having an issue with docker that might have been preventing some gems from being loaded. I'll check back in if I can reproduce it!

**Comment by aycabta** [comment]
@counterbeing Thank you for confirming. If you encounter the problem again and find how to reproduce, please report as a new issue, for that I notice easily.

**Comment by KaitakuShiba** [comment]
https://github.com/ruby/irb/issues/80#issuecomment-616226686
I've reproduced the problem. I specified `irb` at 1.2.1 in Gemfile solves it.
I use `ruby:2.7.1-alpine3.11` image on Docker and exec rspec command.

- trace
```
An error occurred while loading ./spec/models/hoge.rb.
Failure/Error: require File.expand_path('../config/environment', __dir__)

LoadError:
  cannot load such file -- irb/easter-egg
# /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:34:in `require'
# /usr/local/bundle/gems/activesupport-6.0.3.1/lib/active_support/dependencies.rb:324:in `block in require'
# /usr/local/bundle/gems/activesupport-6.0.3.1/lib/active_support/dependencies.rb:291:in `load_dependency'
```

**Comment by VSPPedro** [comment]
I faced the same problem after upgrading Ruby image from 2.6.5 to 2.7.1.

Upgrading IRB to 1.2.4 solved my problem.

Thank you.
